In [12]:
from utils import Dataloader
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
from sklearn.neural_network import MLPClassifier
import time

In [13]:
def array_to_matrix(arr, n_cols):
    n_rows = len(arr) // n_cols
    return np.array(arr).reshape(n_rows, n_cols)

## Iris Dataset

In [26]:
mlp  = MLPClassifier(hidden_layer_sizes=(15,),activation='relu', solver='adam', random_state=1, max_iter=1000)

Iris-setosa + Iris-versicolor

In [4]:
loader = Dataloader(None, None, 'iris', 'Iris-setosa', 'Iris-versicolor')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
start_time = time.time()
mlp.fit(X, y) 
training_time = time.time() - start_time
print("Training time:", training_time, "seconds")

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 0.35866332 -0.62068428  1.1364712   0.91401319]
 [ 0.20204178 -0.19845007  0.85894465  0.91401319]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.82852793 -0.83180138  1.55276101  1.44644806]
 [ 0.04542025 -1.67626978  0.78956302  0.91401319]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 
Training time: 0.5158557891845703 seconds


In [5]:
weights = mlp.coefs_
for i, layer in enumerate(weights):
    print(f"Layer {i}:")
    print(layer.shape)
# print(weights)

Layer 0:
(4, 15)
Layer 1:
(15, 1)


In [6]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]
Accuracy: 1.0


In [7]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


In [8]:
print(X_test)
print(y_test)

[[ 0.82852793 -0.83180138  1.55276101  1.44644806]
 [ 0.04542025 -1.67626978  0.78956302  0.91401319]
 [ 0.6719064   0.22378413  1.3446161   1.80140464]
 [-1.05093052 -0.19845007 -1.01435952 -0.8607697 ]
 [-0.5810659   1.49048673 -0.66745134 -0.68329141]
 [-0.5810659   0.64601833 -0.94497788 -1.03824799]
 [-1.36417359  1.06825253 -1.29188606 -1.03824799]
 [ 0.04542025 -1.46515268  0.65079974  0.55905661]
 [-0.11120129  1.27936963 -0.94497788 -1.03824799]
 [-0.5810659   0.85713543 -1.01435952 -1.03824799]
 [ 0.35866332  1.49048673 -0.80621461 -0.8607697 ]
 [-1.05093052  0.01266703 -0.87559625 -1.03824799]
 [ 0.98514947 -0.62068428  1.27523447  0.7365349 ]
 [ 0.04542025  2.33495513 -1.01435952 -1.03824799]
 [ 0.04542025 -1.04291848  1.06708956  0.7365349 ]
 [-0.73768744  1.06825253 -1.01435952 -1.03824799]
 [ 2.08150023 -0.62068428  1.3446161   1.09149148]
 [ 1.92487869 -0.19845007  1.48337938  1.62392635]
 [-1.05093052 -0.19845007 -1.01435952 -1.21572628]
 [-0.11120129  0.64601833 -0.94

Iris-virginica Iris-versicolor

In [27]:
loader = Dataloader(None, None, 'iris', 'Iris-virginica', 'Iris-versicolor')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp.fit(X, y)

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 2.02877297  0.38660992  2.06223168  1.00321947]
 [-0.39726347  0.38660992 -0.12904165  0.29339437]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.05761837 -0.21746808  0.23617057 -0.41643072]
 [ 0.05761837  0.08457092  0.84485761  0.29339437]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 


MLPClassifier(hidden_layer_sizes=(15,), max_iter=1000, random_state=1)

In [28]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 1 1 0 0]
Accuracy: 0.85


In [29]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.7272727272727273
Recall: 1.0
F1-score: 0.8421052631578948


Iris-setosa Iris-virginica

In [9]:
loader = Dataloader(None, None, 'iris', 'Iris-setosa', 'Iris-virginica')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp.fit(X, y)

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 1.91690205 -0.47344653  1.48387657  1.05511751]
 [ 0.21582425 -0.47344653  0.62004157  0.7271017 ]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.53477633 -0.95655523  0.76401407  0.3990859 ]
 [ 0.53477633 -0.71500088  1.00396823  0.7271017 ]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 


MLPClassifier(hidden_layer_sizes=(15,), max_iter=1000, random_state=1)

In [10]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]
Accuracy: 1.0


In [11]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


## Mushroom Dataset

In [38]:
mushroom = Dataloader(None, None, 'mushroom', None, None)
print(f"Exporting mushroom to python... ")
data = mushroom.export_to_python()

fetching mushroom dataset
Dataset:  mushroom
X_train:  [[-0.21699152  0.14012794 -0.98389939 -0.84322964  1.3573133   0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135  0.68377765
  -0.89305291  0.0965768   0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981 -0.8771691 ]
 [ 1.02971224  0.14012794 -0.19824983 -0.84322964 -1.01956488  0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135 -0.9254372
   0.58638466  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981  1.44858865]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[-0.8403434  -1.48615695 -0.19824983 -0.84322964  0.40656203  0.16289645
   2.27861212 -0.66903831 -0.51147238  0.87351064  0.20869036  0.68377765
  -2.37249048  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574 -0.2504706  -0.5143892  -0.29572966]
 [-0.8403434   0.14012794 -0.98389939 -0.84322964  1.83268894  0.16289645
  -0.43886

c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.loc[:, col] = le.fit_transform(X[col])
c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.loc[:, col] = le.fit_transform(X[col])
c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http

In [39]:

mlp_mushroom = MLPClassifier(hidden_layer_sizes=(150, 100, 2), activation='relu', solver='adam', random_state=1, max_iter=1000)


X_shape = mushroom.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp_mushroom.fit(X, y) 

MLPClassifier(hidden_layer_sizes=(150, 100, 2), max_iter=1000, random_state=1)

In [40]:
# Lấy danh sách các lớp của mạng nơ-ron
layers = mlp_mushroom.coefs_

# In các trọng số của từng lớp
for i, layer in enumerate(layers):
    print(f"Layer {i}:")
    print(layer.shape)
    # print(layer)


Layer 0:
(22, 150)
[[ 0.0131376   0.03998562 -0.18037662 ...  0.04450626 -0.01342022
  -0.1195383 ]
 [-0.15994502  0.22369445  0.03859364 ... -0.16688084  0.09223547
  -0.20753536]
 [ 0.13641009  0.09459517  0.09516024 ...  0.1098084  -0.12645936
  -0.13853506]
 ...
 [-0.09929346  0.2491696  -0.1683041  ...  0.09814125 -0.12037137
  -0.01471266]
 [ 0.04189706 -0.19416033 -0.13614087 ...  0.06211131 -0.05387941
  -0.01377934]
 [-0.25315747  0.11082844 -0.13093246 ...  0.11035356  0.1130053
  -0.01772727]]
Layer 1:
(150, 100)
[[-0.12636975  0.01174368  0.0347975  ...  0.02286907  0.07791981
   0.16876462]
 [ 0.04343723  0.0968511   0.1459661  ... -0.11465372  0.28807324
   0.03849301]
 [-0.04617692  0.06319465  0.10339182 ... -0.0883273   0.06149404
   0.07767751]
 ...
 [-0.06468736 -0.17063213 -0.09269732 ...  0.14419992 -0.14307824
   0.12197697]
 [ 0.14592579  0.08663419  0.04052191 ...  0.04811937 -0.1006657
  -0.05503967]
 [-0.03929291  0.13198818 -0.21959739 ...  0.06815766 -0.0490

In [41]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp_mushroom.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[0 1 1 ... 1 1 1]
Accuracy: 1.0


In [42]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


## MNIST dataset

In [21]:
mnist = Dataloader(None, None, 'mnist', None, None)
print(f"Exporting mnist to python... ")
data = mnist.export_to_python()

Dataset:  mnist
X_train:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_train:  [[ 1. -1.]
 [-1.  1.]]
X_test:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_test:  [[-1.  1.]
 [ 1. -1.]]
(11881, 784) (11881, 2) (2012, 784) (2012, 2)
Exporting mnist to python... 


In [22]:

mlp_mnist = MLPClassifier(hidden_layer_sizes=(150, 100, 2), activation='relu', solver='adam', random_state=1, max_iter=1000)
X_shape = mnist.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp_mnist.fit(X, y) 

MLPClassifier(hidden_layer_sizes=(150, 100, 2), max_iter=1000, random_state=1)

In [23]:
# Lấy danh sách các lớp của mạng nơ-ron
layers = mlp_mnist.coefs_

# In các trọng số của từng lớp
for i, layer in enumerate(layers):
    print(f"Layer {i}:")
    print(layer.shape)
    print(layer)


Layer 0:
(784, 150)
[[-1.18707329e-23 -1.53290399e-20 -4.65896294e-13 ... -9.70641282e-21
  -8.31828986e-25 -2.58650233e-13]
 [-9.07202420e-15  9.30101936e-14  2.24814386e-24 ... -5.33951129e-15
   2.06194910e-13  3.98308644e-18]
 [-1.75805448e-18  2.49757577e-17  8.96588962e-22 ...  3.67435120e-15
   3.59762240e-17  2.35570527e-17]
 ...
 [-1.23221776e-22 -1.10745020e-17  1.30500340e-16 ...  5.92168965e-14
  -1.20528635e-22 -4.07813859e-14]
 [ 4.31458578e-13  4.12746403e-18  1.98635257e-20 ...  1.15806645e-21
   3.45600938e-17  1.33438905e-21]
 [-2.62628891e-17 -1.24885744e-21  3.47342503e-17 ... -2.04360912e-14
  -1.28567718e-21 -1.52281512e-16]]
Layer 1:
(150, 100)
[[-0.13297615 -0.11567363 -0.06260135 ... -0.08208432 -0.07331319
  -0.08249734]
 [ 0.03702546 -0.13429916  0.07972849 ...  0.16061091  0.00542046
  -0.12667974]
 [ 0.11848674  0.09144515  0.03959711 ...  0.1796228   0.02287379
   0.06373644]
 ...
 [-0.10921628 -0.0652903   0.02826685 ...  0.00459555 -0.08943202
   0.10464

In [24]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])
print(X_shape)
y_pred = mlp_mnist.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

(11881, 784)
[1 0 0 ... 1 0 1]
Accuracy: 0.9935387673956262


In [25]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.9970731707317073
Recall: 0.9903100775193798
F1-score: 0.9936801166747691
