In [48]:
from utils import Dataloader
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
from sklearn.neural_network import MLPClassifier
import time

In [49]:
def array_to_matrix(arr, n_cols):
    n_rows = len(arr) // n_cols
    return np.array(arr).reshape(n_rows, n_cols)

## Iris Dataset

In [50]:
mlp  = MLPClassifier(hidden_layer_sizes=(15,),activation='relu', solver='adam', random_state=1, max_iter=1000)

Iris-setosa + Iris-versicolor

In [51]:
loader = Dataloader(None, None, 'iris', 'Iris-setosa', 'Iris-versicolor')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
start_time = time.time()
mlp.fit(X, y) 
training_time = time.time() - start_time
print("Training time:", training_time, "seconds")

fetching iris dataset


(150, 4) (150,)
Dataset:  iris
X_train:  [[ 0.35866332 -0.62068428  1.1364712   0.91401319]
 [ 0.20204178 -0.19845007  0.85894465  0.91401319]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.82852793 -0.83180138  1.55276101  1.44644806]
 [ 0.04542025 -1.67626978  0.78956302  0.91401319]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 
Training time: 0.16049957275390625 seconds


In [52]:
weights = mlp.coefs_
for i, layer in enumerate(weights):
    print(f"Layer {i}:")
    print(layer.shape)
# print(weights)
loss = mlp.loss_curve_ 
print(loss)
print(len(loss))

Layer 0:
(4, 15)
Layer 1:
(15, 1)
[0.7950032333410059, 0.7877308718272474, 0.7805369350343137, 0.7734136081040199, 0.7663475576233808, 0.7593370722084474, 0.752376475210024, 0.7454692383591178, 0.738607162831884, 0.7317897057911993, 0.7250279256999865, 0.7183193248145201, 0.7116623014792461, 0.7050605721486891, 0.6985143582305249, 0.6920255151857528, 0.6855933834120241, 0.6792333408384854, 0.6729093850892429, 0.6666369062015118, 0.6604150628802969, 0.6542572293403621, 0.6481641437794897, 0.6421326896895271, 0.6361693870970924, 0.6302706333123809, 0.6244305311219366, 0.6186469162087774, 0.6129213634644386, 0.6072556943508076, 0.601651828665329, 0.5961040269223397, 0.5905970934314946, 0.5851385170058845, 0.5797277459146531, 0.5743753770624115, 0.5690817685509738, 0.5638525050938541, 0.5586660095897161, 0.5535358568767763, 0.5484611817322077, 0.5434296653900464, 0.5384474690233853, 0.5335168956087245, 0.5286299827432102, 0.5237900709596915, 0.5190066094766498, 0.5142657203640275, 0.509567

In [53]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]
Accuracy: 1.0


In [54]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


In [55]:
print(X_test)
print(y_test)

[[ 0.82852793 -0.83180138  1.55276101  1.44644806]
 [ 0.04542025 -1.67626978  0.78956302  0.91401319]
 [ 0.6719064   0.22378413  1.3446161   1.80140464]
 [-1.05093052 -0.19845007 -1.01435952 -0.8607697 ]
 [-0.5810659   1.49048673 -0.66745134 -0.68329141]
 [-0.5810659   0.64601833 -0.94497788 -1.03824799]
 [-1.36417359  1.06825253 -1.29188606 -1.03824799]
 [ 0.04542025 -1.46515268  0.65079974  0.55905661]
 [-0.11120129  1.27936963 -0.94497788 -1.03824799]
 [-0.5810659   0.85713543 -1.01435952 -1.03824799]
 [ 0.35866332  1.49048673 -0.80621461 -0.8607697 ]
 [-1.05093052  0.01266703 -0.87559625 -1.03824799]
 [ 0.98514947 -0.62068428  1.27523447  0.7365349 ]
 [ 0.04542025  2.33495513 -1.01435952 -1.03824799]
 [ 0.04542025 -1.04291848  1.06708956  0.7365349 ]
 [-0.73768744  1.06825253 -1.01435952 -1.03824799]
 [ 2.08150023 -0.62068428  1.3446161   1.09149148]
 [ 1.92487869 -0.19845007  1.48337938  1.62392635]
 [-1.05093052 -0.19845007 -1.01435952 -1.21572628]
 [-0.11120129  0.64601833 -0.94

Iris-virginica Iris-versicolor

In [56]:
loader = Dataloader(None, None, 'iris', 'Iris-virginica', 'Iris-versicolor')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp.fit(X, y)

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 2.02877297  0.38660992  2.06223168  1.00321947]
 [-0.39726347  0.38660992 -0.12904165  0.29339437]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.05761837 -0.21746808  0.23617057 -0.41643072]
 [ 0.05761837  0.08457092  0.84485761  0.29339437]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 


MLPClassifier(hidden_layer_sizes=(15,), max_iter=1000, random_state=1)

In [57]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 1 1 0 0]
Accuracy: 0.85


In [58]:
loss = mlp.loss_curve_ 
print(loss)

[0.7772026975891775, 0.7717873886590556, 0.7664034158994707, 0.7610611277698213, 0.7557614629711835, 0.7505109632681383, 0.745338428241672, 0.7402152056493523, 0.7351426235586664, 0.73012509583612, 0.7251640503193847, 0.7202645295114466, 0.715418681399614, 0.7106212327203926, 0.7058592558472349, 0.7011322603582524, 0.6964465224793619, 0.6918089716294807, 0.6872397437736146, 0.6827213384031978, 0.6782519900463084, 0.6738213730431759, 0.6694282148163673, 0.665077829523303, 0.6607731499374007, 0.6565158608968925, 0.6523093352556554, 0.6481471292123188, 0.6440292896628205, 0.6399519333493988, 0.6359241161850772, 0.6319431886841701, 0.6280105198516218, 0.6241168093769462, 0.6202686981714384, 0.6164722489874487, 0.6127282565018409, 0.6090401453460095, 0.6053953302981218, 0.6017911204120885, 0.5982262934380546, 0.594702434939164, 0.5912198096376811, 0.5877784147786254, 0.5843804470176073, 0.5810249191103427, 0.5777135506920306, 0.5744426564292232, 0.5712123058906552, 0.5680215043946323, 0.564

In [59]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.7272727272727273
Recall: 1.0
F1-score: 0.8421052631578948


Iris-setosa Iris-virginica

In [60]:
loader = Dataloader(None, None, 'iris', 'Iris-setosa', 'Iris-virginica')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp.fit(X, y)

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 1.91690205 -0.47344653  1.48387657  1.05511751]
 [ 0.21582425 -0.47344653  0.62004157  0.7271017 ]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.53477633 -0.95655523  0.76401407  0.3990859 ]
 [ 0.53477633 -0.71500088  1.00396823  0.7271017 ]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 


MLPClassifier(hidden_layer_sizes=(15,), max_iter=1000, random_state=1)

In [61]:
loss = mlp.loss_curve_ 
print(loss)

[0.8011223984289269, 0.7936508097956056, 0.7862390559996726, 0.7788968353817244, 0.7716312478984348, 0.7644335294599075, 0.7572986332056824, 0.7502325425349746, 0.7432393186536258, 0.7363127880761023, 0.7294492294333514, 0.7226519539760682, 0.7159265368255399, 0.7092711346552186, 0.7026896694403069, 0.6961710612172013, 0.6897201524568204, 0.6833570022358151, 0.677067032040697, 0.6708404383285338, 0.664672734352124, 0.6585727429721718, 0.6525343094475105, 0.646549619277752, 0.6406231766199223, 0.6347632459582757, 0.6289670962566314, 0.623230502777622, 0.6175646798800855, 0.6119695057130695, 0.6064360808808203, 0.6009623842136498, 0.5955459606418164, 0.5901899201734132, 0.5848854418227557, 0.5796319393482505, 0.5744385327876246, 0.5693029325926526, 0.5642205287417518, 0.5592015176271323, 0.554238854126738, 0.549321334309941, 0.5444464922908716, 0.5396078957600846, 0.5348056437013795, 0.5300418448861048, 0.5253230242190404, 0.5206548492761631, 0.5160339956791609, 0.5114645649390666, 0.506

In [62]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]
Accuracy: 1.0


In [63]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


## Mushroom Dataset

In [64]:
mushroom = Dataloader(None, None, 'mushroom', None, None)
print(f"Exporting mushroom to python... ")
data = mushroom.export_to_python()

fetching mushroom dataset


Dataset:  mushroom
X_train:  [[-0.21699152  0.14012794 -0.98389939 -0.84322964  1.3573133   0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135  0.68377765
  -0.89305291  0.0965768   0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981 -0.8771691 ]
 [ 1.02971224  0.14012794 -0.19824983 -0.84322964 -1.01956488  0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135 -0.9254372
   0.58638466  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981  1.44858865]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[-0.8403434  -1.48615695 -0.19824983 -0.84322964  0.40656203  0.16289645
   2.27861212 -0.66903831 -0.51147238  0.87351064  0.20869036  0.68377765
  -2.37249048  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574 -0.2504706  -0.5143892  -0.29572966]
 [-0.8403434   0.14012794 -0.98389939 -0.84322964  1.83268894  0.16289645
  -0.43886364  1.49468272 -1.3588962

c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.loc[:, col] = le.fit_transform(X[col])
c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.loc[:, col] = le.fit_transform(X[col])
c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http

In [65]:

mlp_mushroom = MLPClassifier(hidden_layer_sizes=(150, 100, 2), activation='relu', solver='adam', random_state=1, max_iter=1000)


X_shape = mushroom.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp_mushroom.fit(X, y) 

MLPClassifier(hidden_layer_sizes=(150, 100, 2), max_iter=1000, random_state=1)

In [66]:
loss = mlp_mushroom.loss_curve_ 
print(loss)

[0.4367013282738765, 0.2973056388936893, 0.26214814134595077, 0.24617357490900743, 0.23579137989946275, 0.22763444625424786, 0.22074724887252536, 0.21408365756114767, 0.20802952815104397, 0.20241122220205351, 0.1969549025742592, 0.19178520816863712, 0.18679946212211498, 0.18206480696467436, 0.17743505791025177, 0.17317221130922197, 0.16876069944247854, 0.1646761069988514, 0.16066453982559287, 0.15677866802985727, 0.1530375816899188, 0.14941262083443008, 0.14591682059407515, 0.14250895912090605, 0.1391739256932269, 0.1359861773599788, 0.1328935014071939, 0.12988778348828292, 0.12694243853221837, 0.12409136502307067, 0.12131313404456619, 0.1186231297138705, 0.11601055938472177, 0.1134951450714109, 0.11107289230828779, 0.1086342288397094, 0.10628614378556774, 0.10401538551528548, 0.10180700011217235, 0.09967967281836718, 0.09757866612506677, 0.09555728731421795, 0.09358328431030434, 0.09165476371410149, 0.08977189325853371, 0.08794018260834006, 0.08616282574610883, 0.08443762439628341, 0.

In [67]:
# Lấy danh sách các lớp của mạng nơ-ron
layers = mlp_mushroom.coefs_

# In các trọng số của từng lớp
for i, layer in enumerate(layers):
    print(f"Layer {i}:")
    print(layer.shape)
    # print(layer)


Layer 0:
(22, 150)
Layer 1:
(150, 100)
Layer 2:
(100, 2)
Layer 3:
(2, 1)


In [68]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp_mushroom.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[0 1 1 ... 1 1 1]
Accuracy: 1.0


In [69]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


## MNIST dataset

In [88]:
from utils import Dataloader
mnist = Dataloader(None, None, 'mnist', None, None)
print(f"Exporting mnist to python... ")
data = mnist.export_to_python()

[1 0 1 0 0 1 0 0 1 1]
Dataset:  mnist
X_train:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_train:  [[ 1. -1.]
 [-1.  1.]]
X_test:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_test:  [[-1.  1.]
 [ 1. -1.]]
(12665, 784) (12665, 2) (2115, 784) (2115, 2)
Exporting mnist to python... 


In [89]:

mlp_mnist = MLPClassifier(hidden_layer_sizes=(150, 100, 2), activation='relu', solver='adam', random_state=1, max_iter=1000)
X_shape = mnist.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp_mnist.fit(X, y) 

MLPClassifier(hidden_layer_sizes=(150, 100, 2), max_iter=1000, random_state=1)

In [90]:
loss = mlp_mnist.loss_curve_ 
print(loss)

[0.10095602329130694, 0.003409001912717198, 0.0015081029886822286, 0.0007494766730253629, 0.00048818559342137614, 0.0003989386825165058, 0.0003085814465386173, 0.00023359271825939507, 0.00019602351563095824, 0.00017238757465550298, 0.0001586252266479318, 0.00014749153698184327, 0.00013599626665210598, 0.00013003355171036063, 0.00012393263350977845, 0.00011823713781561198]


In [91]:
# Lấy danh sách các lớp của mạng nơ-ron
layers = mlp_mnist.coefs_

# In các trọng số của từng lớp
for i, layer in enumerate(layers):
    print(f"Layer {i}:")
    print(layer.shape)
    print(layer)


Layer 0:
(784, 150)
[[ 3.91309861e-21  5.76246092e-18 -3.87403397e-11 ...  3.19981792e-18
  -6.53697284e-22 -2.42403995e-11]
 [-1.86861611e-12  1.08436224e-11 -1.92265929e-21 ... -1.27838657e-12
   2.02575377e-11  5.26972239e-16]
 [-6.82955713e-16  9.21234926e-14 -4.47223808e-19 ...  9.84631575e-13
  -1.94359435e-14 -5.90251289e-15]
 ...
 [ 3.51671289e-20  8.38454387e-16  1.46438225e-13 ...  7.64083050e-12
   3.32927433e-20 -5.73784748e-12]
 [ 3.64332733e-11  5.10915708e-16 -9.17552161e-18 ... -4.43112577e-19
  -3.76426339e-14 -5.31338631e-19]
 [ 5.07575801e-14  5.28095137e-19  9.80753283e-14 ... -3.40144852e-12
   4.98216331e-19 -1.55943368e-13]]
Layer 1:
(150, 100)
[[-0.12986352 -0.13198536 -0.06068928 ... -0.09453962 -0.07131752
  -0.08460738]
 [ 0.03816402 -0.09811022  0.05912366 ...  0.14096911  0.01705887
  -0.1128716 ]
 [ 0.11692913  0.09388404  0.0521386  ...  0.15213696  0.0313308
   0.07074859]
 ...
 [-0.11332766 -0.07210476  0.04858068 ... -0.0090965  -0.08788963
   0.101007

In [92]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])
print(X_shape)
y_pred = mlp_mnist.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

(12665, 784)
[1 0 1 ... 1 0 1]
Accuracy: 0.9985815602836879


In [93]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.9973637961335676
Recall: 1.0
F1-score: 0.9986801583809943
