In [31]:
from utils import Dataloader
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
from sklearn.neural_network import MLPClassifier
import time

In [32]:
def array_to_matrix(arr, n_cols):
    n_rows = len(arr) // n_cols
    return np.array(arr).reshape(n_rows, n_cols)

## Iris Dataset

In [33]:
mlp  = MLPClassifier(hidden_layer_sizes=(15,),activation='relu', solver='adam', random_state=1, max_iter=1000)

In [34]:
loader = Dataloader(None, None, 'iris', 'Iris-setosa', 'Iris-versicolor')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
start_time = time.time()
mlp.fit(X, y) 
training_time = time.time() - start_time
print("Training time:", training_time, "seconds")

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 0.35866332 -0.62068428  1.1364712   0.91401319]
 [ 0.20204178 -0.19845007  0.85894465  0.91401319]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.82852793 -0.83180138  1.55276101  1.44644806]
 [ 0.04542025 -1.67626978  0.78956302  0.91401319]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 
Training time: 0.14083600044250488 seconds


In [35]:
weights = mlp.coefs_
print(weights)

[array([[-0.35297048,  0.44391404, -0.82510799,  0.04153432, -0.26860699,
        -0.27195885, -0.15362867,  0.06308722, -0.38500938, -0.22596106,
         0.08527406,  0.15075137, -0.17032114,  0.6440161 , -0.41715672],
       [ 0.35360069, -0.34610438,  0.30470719, -0.65129466, -0.65326245,
         0.20379115,  0.21654416, -0.44240148,  0.42794984,  0.65136556,
         0.21565553, -0.42316617, -0.65101561, -0.65065123,  0.31440501],
       [-0.70243307,  0.14668797,  0.24091665,  0.34158174,  0.38448402,
        -0.02516094,  0.45430318,  0.63890263, -0.81114658,  0.00856872,
         0.74977342,  0.22959075, -0.07208679,  0.58660082, -0.33149689],
       [-0.30533588,  0.70093634, -0.5048161 ,  0.06499411, -0.25485232,
        -0.36020616,  0.44724131, -0.0613669 , -0.53207225, -0.28462148,
        -0.2993805 ,  0.0349138 , -0.22450733,  0.36885316,  0.33857177]]), array([[-0.72994492],
       [ 0.80702747],
       [-0.51139793],
       [ 0.66585486],
       [ 0.19043734],
       

In [36]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]
Accuracy: 1.0


In [37]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


## Mushroom Dataset

In [38]:
mushroom = Dataloader(None, None, 'mushroom', None, None)
print(f"Exporting mushroom to python... ")
data = mushroom.export_to_python()

fetching mushroom dataset
Dataset:  mushroom
X_train:  [[-0.21699152  0.14012794 -0.98389939 -0.84322964  1.3573133   0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135  0.68377765
  -0.89305291  0.0965768   0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981 -0.8771691 ]
 [ 1.02971224  0.14012794 -0.19824983 -0.84322964 -1.01956488  0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135 -0.9254372
   0.58638466  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981  1.44858865]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[-0.8403434  -1.48615695 -0.19824983 -0.84322964  0.40656203  0.16289645
   2.27861212 -0.66903831 -0.51147238  0.87351064  0.20869036  0.68377765
  -2.37249048  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574 -0.2504706  -0.5143892  -0.29572966]
 [-0.8403434   0.14012794 -0.98389939 -0.84322964  1.83268894  0.16289645
  -0.43886

c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.loc[:, col] = le.fit_transform(X[col])
c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.loc[:, col] = le.fit_transform(X[col])
c:\Users\ACER\Documents\AI\KDL\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http

In [39]:

mlp_mushroom = MLPClassifier(hidden_layer_sizes=(150, 100, 2), activation='relu', solver='adam', random_state=1, max_iter=1000)


X_shape = mushroom.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp_mushroom.fit(X, y) 

MLPClassifier(hidden_layer_sizes=(150, 100, 2), max_iter=1000, random_state=1)

In [40]:
# Lấy danh sách các lớp của mạng nơ-ron
layers = mlp_mushroom.coefs_

# In các trọng số của từng lớp
for i, layer in enumerate(layers):
    print(f"Layer {i}:")
    print(layer.shape)
    print(layer)


Layer 0:
(22, 150)
[[ 0.0131376   0.03998562 -0.18037662 ...  0.04450626 -0.01342022
  -0.1195383 ]
 [-0.15994502  0.22369445  0.03859364 ... -0.16688084  0.09223547
  -0.20753536]
 [ 0.13641009  0.09459517  0.09516024 ...  0.1098084  -0.12645936
  -0.13853506]
 ...
 [-0.09929346  0.2491696  -0.1683041  ...  0.09814125 -0.12037137
  -0.01471266]
 [ 0.04189706 -0.19416033 -0.13614087 ...  0.06211131 -0.05387941
  -0.01377934]
 [-0.25315747  0.11082844 -0.13093246 ...  0.11035356  0.1130053
  -0.01772727]]
Layer 1:
(150, 100)
[[-0.12636975  0.01174368  0.0347975  ...  0.02286907  0.07791981
   0.16876462]
 [ 0.04343723  0.0968511   0.1459661  ... -0.11465372  0.28807324
   0.03849301]
 [-0.04617692  0.06319465  0.10339182 ... -0.0883273   0.06149404
   0.07767751]
 ...
 [-0.06468736 -0.17063213 -0.09269732 ...  0.14419992 -0.14307824
   0.12197697]
 [ 0.14592579  0.08663419  0.04052191 ...  0.04811937 -0.1006657
  -0.05503967]
 [-0.03929291  0.13198818 -0.21959739 ...  0.06815766 -0.0490

In [41]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = mlp_mushroom.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[0 1 1 ... 1 1 1]
Accuracy: 1.0


In [42]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 1.0
Recall: 1.0
F1-score: 1.0


## MNIST dataset

In [43]:
mnist = Dataloader(None, None, 'mnist', None, None)
print(f"Exporting mnist to python... ")
data = mnist.export_to_python()

Dataset:  mnist
X_train:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_train:  [[ 1. -1.]
 [-1.  1.]]
X_test:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_test:  [[-1.  1.]
 [ 1. -1.]]
(11881, 784) (11881, 2) (2012, 784) (2012, 2)
Exporting mnist to python... 


In [44]:

mlp_mnist = MLPClassifier(hidden_layer_sizes=(150, 100, 2), activation='relu', solver='adam', random_state=1, max_iter=1000)
X_shape = mnist.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
mlp_mnist.fit(X, y) 

MLPClassifier(hidden_layer_sizes=(150, 100, 2), max_iter=1000, random_state=1)

In [45]:
# Lấy danh sách các lớp của mạng nơ-ron
layers = mlp_mushroom.coefs_

# In các trọng số của từng lớp
for i, layer in enumerate(layers):
    print(f"Layer {i}:")
    print(layer.shape)
    print(layer)


Layer 0:
(22, 150)
[[ 0.0131376   0.03998562 -0.18037662 ...  0.04450626 -0.01342022
  -0.1195383 ]
 [-0.15994502  0.22369445  0.03859364 ... -0.16688084  0.09223547
  -0.20753536]
 [ 0.13641009  0.09459517  0.09516024 ...  0.1098084  -0.12645936
  -0.13853506]
 ...
 [-0.09929346  0.2491696  -0.1683041  ...  0.09814125 -0.12037137
  -0.01471266]
 [ 0.04189706 -0.19416033 -0.13614087 ...  0.06211131 -0.05387941
  -0.01377934]
 [-0.25315747  0.11082844 -0.13093246 ...  0.11035356  0.1130053
  -0.01772727]]
Layer 1:
(150, 100)
[[-0.12636975  0.01174368  0.0347975  ...  0.02286907  0.07791981
   0.16876462]
 [ 0.04343723  0.0968511   0.1459661  ... -0.11465372  0.28807324
   0.03849301]
 [-0.04617692  0.06319465  0.10339182 ... -0.0883273   0.06149404
   0.07767751]
 ...
 [-0.06468736 -0.17063213 -0.09269732 ...  0.14419992 -0.14307824
   0.12197697]
 [ 0.14592579  0.08663419  0.04052191 ...  0.04811937 -0.1006657
  -0.05503967]
 [-0.03929291  0.13198818 -0.21959739 ...  0.06815766 -0.0490

In [46]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])
print(X_shape)
y_pred = mlp_mnist.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

(11881, 784)
[1 0 0 ... 1 0 1]
Accuracy: 0.9935387673956262


In [47]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.9970731707317073
Recall: 0.9903100775193798
F1-score: 0.9936801166747691
