In [ ]:
from utils import Dataloader
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
def array_to_matrix(arr, n_cols):
    n_rows = len(arr) // n_cols
    return np.array(arr).reshape(n_rows, n_cols)

## Iris Dataset

In [3]:
C = 1.0
clf = SVC(kernel = 'linear', C = C)

#### Iris-setosa & Iris-versicolor

In [4]:
loader = Dataloader(None, None, 'iris', 'Iris-setosa', 'Iris-versicolor')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
clf.fit(X, y) 

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 0.35866332 -0.62068428  1.1364712   0.91401319]
 [ 0.20204178 -0.19845007  0.85894465  0.91401319]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.82852793 -0.83180138  1.55276101  1.44644806]
 [ 0.04542025 -1.67626978  0.78956302  0.91401319]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 


SVC(kernel='linear')

#### Iris-setosa & Iris-virginica

In [5]:
loader = Dataloader(None, None, 'iris', 'Iris-setosa', 'Iris-virginica')
print(f"Exporting iris to python... ")
data = loader.export_to_python()
X_shape = loader.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
clf.fit(X, y) 

fetching iris dataset
(150, 4) (150,)
Dataset:  iris
X_train:  [[ 1.91690205 -0.47344653  1.48387657  1.05511751]
 [ 0.21582425 -0.47344653  0.62004157  0.7271017 ]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[ 0.53477633 -0.95655523  0.76401407  0.3990859 ]
 [ 0.53477633 -0.71500088  1.00396823  0.7271017 ]]
y_test:  [[-1.  1.]
 [-1.  1.]]
(80, 4) (80, 2) (20, 4) (20, 2)
Exporting iris to python... 


SVC(kernel='linear')

#### Result

In [5]:
w_sklearn = clf.coef_.reshape(-1, 1)
b_sklearn = clf.intercept_[0]
print('W =',w_sklearn.T)
print('b =',b_sklearn)

W = [[ 0.26980793 -0.33827267  0.70021528  0.74918027]]
b = 0.2470183358436795


#### Test

In [6]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]
Accuracy: 1.0


## Mushroom Dataset

In [11]:
mushroom = Dataloader(None, None, 'mushroom', None, None)
print(f"Exporting mushroom to python... ")
data = mushroom.export_to_python()

fetching mushroom dataset
Dataset:  mushroom
X_train:  [[-0.21699152  0.14012794 -0.98389939 -0.84322964  1.3573133   0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135  0.68377765
  -0.89305291  0.0965768   0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981 -0.8771691 ]
 [ 1.02971224  0.14012794 -0.19824983 -0.84322964 -1.01956488  0.16289645
  -0.43886364  1.49468272 -1.35889624  0.87351064  1.35578135 -0.9254372
   0.58638466  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574  1.42842641  0.28432981  1.44858865]]
y_train:  [[-1.  1.]
 [-1.  1.]]
X_test:  [[-0.8403434  -1.48615695 -0.19824983 -0.84322964  0.40656203  0.16289645
   2.27861212 -0.66903831 -0.51147238  0.87351064  0.20869036  0.68377765
  -2.37249048  0.62244139  0.63199138  0.          0.14203663 -0.25613174
  -1.27221574 -0.2504706  -0.5143892  -0.29572966]
 [-0.8403434   0.14012794 -0.98389939 -0.84322964  1.83268894  0.16289645
  -0.43886

d:\Study\kì-2-năm-4\Kho dữ liệu và khai phá dữ liệu\Code\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.loc[:, col] = le.fit_transform(X[col])
d:\Study\kì-2-năm-4\Kho dữ liệu và khai phá dữ liệu\Code\KDL\utils.py:184: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.loc[:, col] = le.fit_transform(X[col])
d:\Study\kì-2-năm-4\Kho dữ liệu và khai phá dữ liệu\Code\KDL\utils.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = v

In [16]:
C = 10.0
clf_mushroom = SVC(kernel = 'linear', C = C)
X_shape = mushroom.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
clf_mushroom.fit(X, y) 


SVC(C=10.0, kernel='linear')

In [17]:
w_sklearn = clf_mushroom.coef_.reshape(-1, 1)
b_sklearn = clf_mushroom.intercept_[0]
print('W =',w_sklearn.T)
print('b =',b_sklearn)

W = [[ 1.22625129e-04  6.23561682e-03 -5.46300858e-05 -1.28255241e+00
  -4.92932545e-01 -2.31352356e-04 -4.13115649e+00  4.67374517e+00
  -3.41542738e-03  1.18849502e+00 -4.76928428e+00 -1.61030131e+00
  -8.89066912e-05  6.75801530e-05  1.18736958e-04  0.00000000e+00
   3.30996475e-01  1.20129837e+00 -4.41814231e-01 -2.52010211e-02
  -2.48274160e+00 -1.78908142e-04]]
b = -1.0128541204582493


In [18]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])

y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

[0 1 1 ... 1 1 1]
Accuracy: 0.9655384615384616


## MNIST dataset

In [20]:
mnist = Dataloader(None, None, 'mnist', None, None)
print(f"Exporting mnist to python... ")
data = mnist.export_to_python()

Dataset:  mnist
X_train:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_train:  [[ 1. -1.]
 [-1.  1.]]
X_test:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_test:  [[-1.  1.]
 [ 1. -1.]]
(11881, 784) (11881, 2) (2012, 784) (2012, 2)
Exporting mnist to python... 


In [21]:
C = 1.0
clf_mnist = SVC(kernel = 'linear', C = C)
X_shape = mnist.X_train_shape
X_train = data[0]
y_train = data[1]
y = array_to_matrix(y_train,2)
X = array_to_matrix(X_train,X_shape[1])
y = np.array([np.argmax(np.append(i,0)) for i in y])
clf_mnist.fit(X, y) 

SVC(kernel='linear')

In [25]:
X_test = array_to_matrix(data[2],X_shape[1])
y_test = array_to_matrix(data[3],2)
y_test = np.array([np.argmax(np.append(i,0)) for i in y_test])
print(X_shape)
y_pred = clf_mnist.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(y_pred)
print("Accuracy:", accuracy)

(11881, 784)
[1 0 0 ... 1 0 1]
Accuracy: 0.9850894632206759
